language: python
python:
  - "2.7"
before_install:  # http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - npm install -g bower
  - pip install -r requirements/dev.txt
script:
  - python manage.py bower install
  - py.test
